#!/usr/bin/env python3
# bin2h.py <in.bin> <out.h> <symbol> — フラットバイナリを C ヘッダ (const 配列 + _LEN) へ。
# shell.bin → native/dos_shell_blob.h の生成に使う (build.sh から呼ぶ)。
import sys

def main():
    if len(sys.argv) != 4:
        sys.exit("usage: bin2h.py <in.bin> <out.h> <symbol>")
    inp, outp, sym = sys.argv[1], sys.argv[2], sys.argv[3]
    data = open(inp, "rb").read()
    guard = sym.upper() + "_H"
    lines = [
        "/* GENERATED by tools/dos_loader/build.sh (bin2h.py) from shell.asm — DO NOT EDIT. */",
        f"#ifndef {guard}",
        f"#define {guard}",
        f"static const unsigned char {sym}[] = {{",
    ]
    for i in range(0, len(data), 12):
        chunk = data[i:i + 12]
        lines.append("    " + " ".join(f"0x{b:02x}," for b in chunk))
    lines.append("};")
    lines.append(f"#define {sym.upper()}_LEN {len(data)}u")
    lines.append(f"#endif /* {guard} */")
    open(outp, "w").write("\n".join(lines) + "\n")
    print(f"OK: {outp} ({len(data)} bytes, symbol {sym})")

if __name__ == "__main__":
    main()
